### PR TITLE
added productfeatures to StartSession params

### PR DESCRIPTION
**Pull request by ssendev**
i have a new "eyefi mobiPRO 32GB+WiFi SDHC class10" and it failed to upload images because it is sending a productfeatures param.

this patch allows this extra param.

### CODE REVIEW

**Comment by kristofg** [comment]
Thanks!  I'm wondering, though:  What does the content of the productfeatures field look like?  Would it make sense to do stricter checking of the contents than /.*/?

**Comment by ssendev** [comment]
i don't know. perl isn't really my language so i made the simplest change i could.

**Comment by kristofg** [comment]
But what did the field look like when you tested this?  I have no eye-fi cards in operation any more, so I'm unable to test this myself.

**Comment by ssendev** [comment]
i got an error that line 1207 caused a validation failure because there is an extra field with name productfeatures. i never saw the contents of the field and have no clue how i could display them. i am also not certain if the way i added the field causes validation errors with older cards which don't have the field. but again i didn't  know enough perl to do anyting about it.

**Comment by ssendev** [comment]
ok today i was a little less lazy and checked it. productfeatures contains `127` so is probably a number. i also confirmed that it would indeed break old cards and have made the field optional.

**Comment by kristofg** [comment]
Thanks, the extra research is really appreciated.  This looks like a pretty straightforward fix now.

**Pull request merged**
